---
- name: Install
  ansible.builtin.package:
    name:
      - jq
      - dog
      - open-iscsi
      - nfs-utils
    state: latest
  become: yes

- name: Set sudo
  ansible.builtin.replace:
    path: "/etc/sudoers.d/10-installer"
    regexp: '\%wheel ALL=\(ALL\) ALL'
    replace: '%wheel ALL=(ALL) NOPASSWD: ALL'
  become: yes

- name: Set hosts
  ansible.builtin.template:
    dest: "/etc/hosts"
    src: hosts.j2
  become: yes
