---
- name: Install
  ansible.builtin.package:
    name:
      - kitty
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Configuration
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    src: "kitty.conf.j2"

- name: Themes 
  copy:
    dest: "{{ ansible_user_dir }}/.config/kitty"
    src: "{{ kitty_config_item }}"
  loop_control:
    loop_var: kitty_config_item
  with_fileglob:
    - "kitty_*"
